-- Hàm tạo ID loại độc giả tự động
CREATE FUNCTION AUTO_IDLOAIDOCGIA()

RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaLoaiDocGia) FROM LOAIDOCGIA) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaLoaiDocGia, 4)) FROM LOAIDOCGIA
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9    THEN 'LD000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 and @ID < 99   THEN 'LD00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 99 and @ID < 999 THEN 'LD0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999              THEN 'LD' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END


-- Hàm tạo ID độc giả tự động
CREATE FUNCTION AUTO_IDDOCGIA()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaDocGia) FROM DOCGIA) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaDocGia, 4)) FROM DOCGIA
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9   THEN 'DG000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 and @ID < 99  THEN 'DG00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 0 and @ID < 999 THEN 'DG0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999             THEN 'DG' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

-- Hàm tạo ID thể loại
CREATE FUNCTION AUTO_IDTHELOAI()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaTheLoai) FROM THELOAI) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaTheLoai, 4)) FROM THELOAI
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9   THEN 'TL000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 and @ID < 99  THEN 'TL00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 0 and @ID < 999 THEN 'TL0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999             THEN 'TL' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

-- Hàm tạo ID sách
CREATE FUNCTION AUTO_IDSACH()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaSach) FROM SACH) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaSach, 4)) FROM SACH
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9   THEN 'SA000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 and @ID < 99  THEN 'SA00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 0 and @ID < 999 THEN 'SA0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999             THEN 'SA' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
-- Hàm tạo ID tình trạng
CREATE FUNCTION AUTO_IDTINHTRANG()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaTinhTrang) FROM TINHTRANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaTinhTrang, 4)) FROM TINHTRANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9   THEN 'TT000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 and @ID < 99  THEN 'TT00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 0 and @ID < 999 THEN 'TT0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999             THEN 'TT' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO
-- Hàm tạo ID phiếu mượn sách
CREATE FUNCTION AUTO_IDPHIEUMUONSACH()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MaPhieu) FROM PHIEUMUONSACH) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MaPhieu, 4)) FROM PHIEUMUONSACH
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9   THEN 'PM000' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 and @ID < 99  THEN 'PM00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 0 and @ID < 999 THEN 'PM0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 999             THEN 'PM' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
GO

